USE [master]
GO

/****** Object:  Database [ABC Employee-Job]    Script Date: 4/20/2020 13:40:42 ******/
CREATE DATABASE [ABC Employee-Job]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ABC Employee-Job', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER2017\MSSQL\DATA\ABC Employee-Job.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ABC Employee-Job_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER2017\MSSQL\DATA\ABC Employee-Job_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ABC Employee-Job].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ABC Employee-Job] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET ARITHABORT OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ABC Employee-Job] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ABC Employee-Job] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ABC Employee-Job] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ABC Employee-Job] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET RECOVERY FULL 
GO

ALTER DATABASE [ABC Employee-Job] SET  MULTI_USER 
GO

ALTER DATABASE [ABC Employee-Job] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ABC Employee-Job] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ABC Employee-Job] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ABC Employee-Job] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ABC Employee-Job] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ABC Employee-Job] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ABC Employee-Job] SET  READ_WRITE 
GO

